### ISSUE TITLE
ShopGuiPlus lag issue

### ISSUE THREAD

**Issue by LuluxClient** [Auxilor/EcoEnchants#124]
**Describe the bug**
When having the autosell enchants for some reasons eco and all his variants (ecoitems ...) are making the server lag

**To Reproduce**
1. Enchant an hoe with Autosell
2. Have the potato crop as a sellable crop in the shop
3. Farm some potatoes 
4. Server is lagging

**Expected behavior**
The server shouldn't lag

**Screenshots**
Timings : https://spark.lucko.me/rxg2CiVii2

**Server Information (please complete the following information):**
- Version: This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)
You are running the latest version
- Version of plugin and eco 
Eco: 6.20.4
EcoEnchants 8.29.4

**Additional context**
This lag issue is on every eco plugins

**Comment by WillFP** [comment]
Fixed
