### ISSUE TITLE
Preservation Enchant Issues

### ISSUE THREAD

**Issue by btjt97** [Auxilor/EcoEnchants#126]
**Describe the bug**
Migrating Two Reports: Preservation isn't acting as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/98480009/151211125-d88a1ce6-7caf-4f19-aff7-a612d098ebea.png)

**Server Information (please complete the following information):**
- Version: latest

**Additional context**
Two reports, limited info, seems like it could be conflicting with other protections

**Comment by WillFP** [comment]
Fixed in 8.29.6
