### ISSUE TITLE
Show level requirements on anvil

### ISSUE THREAD

**Issue by PugglesLesser** [Auxilor/EcoEnchants#127]
When combining books or items with enchants, the vanilla level cap can easily be exceeded. This is not a major issue since it allows you to combine them anyway, but there's no way of knowing how many levels it will take.

I would like a marker in the lore of the item which shows the level requirement, much like how https://www.spigotmc.org/resources/overleveled-enchanter.93379/ does it. 

An alternative would be to create an entirely new UI for combining these enchants, but that may break up the flow of vanilla gameplay. It could be an alternative for servers that want something like this though. 

![image](https://user-images.githubusercontent.com/12466796/151232926-eaf28c03-4564-4d35-ad0b-7e041980bfda.png)

**Comment by AlternativeSoap** [comment]
That would be so great!
