### ISSUE TITLE
API + soulbound detection

### ISSUE THREAD

**Issue by mfnalex** [Auxilor/EcoEnchants#13]
Hello :)

I am the author of AngelChest and I was asked to add detection for your SoulBound items. I could not find a maven repo for your plugin when checking quickly, so I am wondering whether there is one to add your plugin as dependency, and if yes, if it's possible to detect your custom soulbound items so I can excempt them from being put into the AngelChests. Please let me know if you need further information. Thanks in advance for your reply! :)

**Comment by Auxilor** [comment]
Hi! Join my discord: https://discord,gg/ZcwpSsE - I'll help you ouit
