### ISSUE TITLE
Soulbound not working on Restart

### ISSUE THREAD

**Issue by Miryex** [Auxilor/EcoEnchants#130]
If you die with an Item that has the Soulbound enchant and the Server restarts while 
the player still hasn't respawned, the item will be deleted. 

1. Enchant an Item with Soulbound
2. Kill yourself with that Item (And don't click Respawn)
3. Restart the Server
4. Rejoin after Restart (The Item will be deleted)

Server Information:
- Version: Paper version git-Paper-175 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9490475)
- eco-6.20.4-all, EcoEnchants v8.29.2

Additional contex
The Enchants seems to also bug and not work sometimes, but I'm not sure why.

**Comment by 0ft3n** [comment]
This is obvious and normal, you are not supposed to refuse clicking "respawn" until server restarts or anything

**Comment by Miryex** [comment]
The Problem is that with using a combatlog Plugin that kills Player when leaving the Server, they will lose the items if they 
dont rejoin before the a restart happens. But I understand that this isn't a fault that has to be fixed since the Plugin isn't made
to work with combatlog.
