### ISSUE TITLE
Compatible with Slimefun

### ISSUE THREAD

**Issue by AlternativeSoap** [Auxilor/EcoEnchants#132]
**Describe the bug**
The hard-cap enchantments on one tools (quantity of enchantments) doesn't work inside Auto Enchanter.. Slimefun Auto Enchanter doesn't respect it

**To Reproduce**
1. Go to 'ecoenchants and set a max cap'
2. Use your auto enchanter on a tool
3. Get unlimited enchantments on one item
4. No errors.

Every config in EcoEnchants doesn't make a work around on Slimefun.

**Expected behavior**
A message that says you can't get more enchantments, something that just stops getting iver example 8 enchantments on one tool

Got a ticket at Discord EcoEnchants. Most of the information is there.
Got more here;
https://github.com/Slimefun/Slimefun4/issues/3447#issuecomment-1025248053

**Server Information (please complete the following information):**
- Version: Paper 177
- Eco; 6.21.1
- EcoEnchants; 8.32.0

**Comment by AlternativeSoap** [comment]
Will this ever be fixed?

**Comment by Texbio** [comment]
ignore this, this is the wrong one.
