### ISSUE TITLE
enchant names of the customenchants.yml file visible in 1.8

### ISSUE THREAD

**Issue by Redwolf223** [Auxilor/EcoEnchants#134]
**Describe the bug**
When you try to enchant an item with a customenchant his name will appear two times on the enchanted item.

**To Reproduce**
1. Enchant an item in 1.8 with a customenchant

**Expected behavior**
Just the Enchant name to be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/58572866/152245992-bd2cb162-20c0-4d8e-88e3-290f375d285b.png)

**Server Information (please complete the following information):**
- Version: EcoEnchants 8.32.3, Eco 6.32.0

**Comment by WillFP** [comment]
I don't support 1.8, I have no idea how you even got it working
