### ISSUE TITLE
EcoEnchants causing crashes?

### ISSUE THREAD

**Issue by cloakfox** [Auxilor/EcoEnchants#137]
https://gist.github.com/cloakfox/9b756a93b8664a9f720849a788baa173

Running eco: 6.22.3
Running ecoenchants: 8.32.3
On paper 1.18.1

Let me know if whole log needs to be provided.

**Comment by WillFP** [comment]
I don't think eco / EcoEnchants / etc is causing the crashes, it's just because of the packet listeners being ran so frequently that they will almost always show up in a thread dump

**Comment by cloakfox** [comment]
I think our players found a way to crash the server using one of the enchants, also if what you say is true it would make logs like mine just useless, I highly doubt that is the case.

**Comment by cloakfox** [comment]
"Ok if u dont belive me then ig I will stay banned, but if the server crashes again then u know it couldent have been me. All I know atm about the crash is that it uses enchanted books, like A LOT OF THEM. I am not quite sure from there on but if u unban me I could work towards finding out how to replicate it and will report it the second I find it. If i dont then just perm ban me forever..."

~ Player we banned this morning for doing these crashes

It looks like it's caused by eco to me, what I think is happening is some player has a book with an absurdly large amount of JSON in it, and when the server tries to parse it it hangs. Not really eco's fault per se as the parsing is done from within the server itself, but eco is making the method call..

**Comment by cloakfox** [comment]
Bump

https://gist.github.com/cloakfox/b67c37746210a919ce9b117552344373
