### ISSUE TITLE
farmhand bug

### ISSUE THREAD

**Issue by yellow-pillow** [Auxilor/EcoEnchants#147]
**Describe the bug**
If you have a hoe with a farmhand enchantment in your left hand, any object will break the first time you dig in the ground (video)

**To Reproduce**
Repeat what's on the video

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://drive.google.com/file/d/14wPg5kM8Q9N2WNVELRGLxZ5_vZj8BdVT/view?usp=sharing)

**Server Information (please complete the following information):**
- Version: 
![image](https://user-images.githubusercontent.com/90108493/153277345-ea73a69f-ff38-49df-8740-a7212c4164c6.png)

- Version of plugin and eco
![image](https://user-images.githubusercontent.com/90108493/153277469-fa6c3e17-9b4b-4d75-a949-70f1d1557a51.png)
![image](https://user-images.githubusercontent.com/90108493/153277523-c81b62da-e3de-424e-9097-0878609e8d79.png)

**Comment by LoJoSho** [comment]
@WillFP This issue should be closed as it was fixed.
