### ISSUE TITLE
customenchants.yml is nonfunctional

### ISSUE THREAD

**Issue by KermX** [Auxilor/EcoEnchants#154]
**Describe the bug**
Enchantments added through customenchants.yml are non functional. Enchants added via this method appear in game as they should and can be attached to their target but will never trigger

**To Reproduce**
2. add an enchant in customenchants.yml (default config is also not functional so that works too)
3. try and use said enchant

**Expected behavior**
these should work

**Screenshots**
N/A

**Server Information (please complete the following information):**
This server is running Paper version git-Paper-187 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 0cc2503)
eco version 6.24.2
EcoEnchants v8.39.0

**Additional context**
Confirmed by **numerous** people in discord

**Comment by WillFP** [comment]
Regenerate target.yml, you're missing the slots (see the wiki)
