### ISSUE TITLE
Intellect not compatible with Soulbound

### ISSUE THREAD

**Issue by thedarkonekiller** [Auxilor/EcoEnchants#160]
When a item with intellect enchant apply, we don't have possible to apply soulbound book in an anvil

- Version: Current: git-Purpur-1558 (MC: 1.18.1)

- Version of plugin and eco 
- eco : 6.24.3
- ecoenchants : 8.39.4

**Comment by WillFP** [comment]
Not a bug, you can only have 1 special enchant on an item by default. You can change that in config.yml
