### ISSUE TITLE
LootPopulator causes IllegalStateException server crash

### ISSUE THREAD

**Issue by luizsusin** [Auxilor/EcoEnchants#162]
**Describe the bug**
LootPopulator is trying to modify a container inventory on an (still) unloaded chunk.

**To Reproduce**
This happens randomly, majorly because sometimes the chunk is loaded when it tries to populate the containers.

**Expected behavior**
LootPopulator should wait for the chunk to be loaded.

**Crash Report**
https://gist.github.com/luizsusin/faef3fd8361f6f8e918586987b7100b9

**Server Information (please complete the following information):**
- Version: Purpur 1.18.1 b1559
- Version of EcoEnchants: 8.39
- Version of Eco: 6.24.2

**Additional context**
Addicional info can be found on https://github.com/PurpurMC/Purpur/issues/916#issuecomment-1043977297

**Comment by WillFP** [comment]
Fixed in next update
