### ISSUE TITLE
EcoEnchants Lore is not hidden when using the hide enchants flag

### ISSUE THREAD

**Issue by KaiserTheGamer** [Auxilor/EcoEnchants#163]
**Describe the bug**
When attempting to hide the enchantments flags when creating custom items the enchantment lore from the plugin persists.

**To Reproduce**
1. Spawn in an item with the hide enchantments flag
2. enchant it with an EcoEnchant
3. See error

**Expected behavior**
The expected behavior is for the item to have no lore pertaining to the enchantment.

**Screenshots**
https://imgur.com/a/GIwiVL4

**Server Information (please complete the following information):**
This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)
You are running the latest version
Previous version: git-Paper-402 (MC: 1.17.1)
Eco ver 6.25.1
EcoEnchants ver 8.39.6

**Additional context**

**Comment by Darkw1nged** [comment]
This is due to the enchantment being added to the lore instead of the Enchantment list as it is not an official minecraft Enchantment.

**Comment by KaiserTheGamer** [comment]
For a while I was able to fix this issue with an option in the eco plugin, and everything worked fine, but after updating to the latest version recently it stopped working

**Comment by WillFP** [comment]
> This is due to the enchantment being added to the lore instead of the Enchantment list as it is not an official minecraft Enchantment.

that's completely wrong. ecoenchants uses real enchantments, not shitty lore lines.

**Comment by WillFP** [comment]
If you add ghast tear into a target in target.yml, this should be fixed? let me know

**Comment by Darkw1nged** [comment]
> > This is due to the enchantment being added to the lore instead of the Enchantment list as it is not an official minecraft Enchantment.
> 
> that's completely wrong. ecoenchants uses real enchantments, not shitty lore lines.

I do not mean that enchant is added to the lore and gets handled from there. I know it is Minecraft enchant but I mean even if it is an enchant you still need to add it to the lore, am I correct?

**Comment by WillFP** [comment]
> > > This is due to the enchantment being added to the lore instead of the Enchantment list as it is not an official minecraft Enchantment.
> > 
> > 
> > that's completely wrong. ecoenchants uses real enchantments, not shitty lore lines.
> 
> I do not mean that enchant is added to the lore and gets handled from there. I know it is Minecraft enchant but I mean even if it is an enchant you still need to add it to the lore, am I correct?

That's handled by the display system, and it has support for hide_enchants. It's always worked for me and many others, and I'm not sure why it isn't here.
