### ISSUE TITLE
Plugin error on version higher than 8.32.0

### ISSUE THREAD

**Issue by boristran03** [Auxilor/EcoEnchants#164]
https://pastebin.com/0sehpSZD
i updated eco and ecoenchants to latest version but still get this error, on old version it work fine, i just got this error since i update ecoenchants to version higher than 8.32.0, i opened a ticket for more than 2 weeks but the author didn't reply lol

**Comment by WillFP** [comment]
Probably a plugin conflict. I've about had it with loader issues like this, going to have to do something i don't want to :/

**Comment by boristran03** [comment]
how can i find which plugin is conflict :"//

**Comment by boristran03** [comment]
oh not a plugin config, i remove all plugin exclude protocolib, eco and ecoenchangs but still get this error message

**Comment by boristran03** [comment]
> Probably a plugin conflict. I've about had it with loader issues like this, going to have to do something i don't want to :/

Can you tell author to read my ticket, this is not a plugin conflict, i tried to remove all plugin exclude eco, ecoenchants and protocolib but still get this error

**Comment by WillFP** [comment]
I **am** the author, can you send me the full latest.log?

**Comment by boristran03** [comment]
> I **am** the author, can you send me the full latest.log?

pastebin.com/MVjgGx0u
