### ISSUE TITLE
Telekinesis bypasses DeathChests from AngelChests

### ISSUE THREAD

**Issue by RebelMythik** [Auxilor/EcoEnchants#166]
**Describe the bug**
When a player kills another with telekinesis on their sword the items will go straight to their inventory instead of spawning a deathchest of the player killed.
**To Reproduce**
1. Have Telekinesis on your sword
2. Kill other player

**Expected behavior**
items would go into the deathchest and not to the person who killed them

**Server Information (please complete the following information):**
- Version: (output of `/ver` command) Current: git-Purpur-1551 (MC: 1.18.1)*
- Version of plugin and eco (`/ver eco`, `/ver <plugin>`) eco version 6.20.4

**Comment by WillFP** [comment]
Disable telekinesis for players in telekinesis.yml
