### ISSUE TITLE
EcoEnchants has a weird item drop

### ISSUE THREAD

**Issue by LuluxClient** [Auxilor/EcoEnchants#170]
**Describe the bug**
When breaking a block ecoenchants is making it so it will always drop in the middle of the block. Because of that it's quite annoying for skyblock and more stuff. 

**To Reproduce**
1. Mine a block
2. do /plugman unload ecoenchants
3. mine a block
4. See the difference

**Expected behavior**
It should be the default way of dropping items

**Screenshots**
https://gyazo.com/dbebfa57c017147106bee12a56b8797a

**Server Information (please complete the following information):**
- Version: (output of `/ver` command)
This server is running Paper version git-Paper-409 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: c53577e on ver/1.17.1)
You are running the latest version

- Version of plugin and eco (`/ver eco`, `/ver <plugin>`)
eco version 6.25.2
EcoEnchants version 8.41.0

**Additional context**

**Comment by WillFP** [comment]
Disable advanced.force-dropqueue in config.yml
