### ISSUE TITLE
Soulbound not working with netherite tools + bows

### ISSUE THREAD

**Issue by Fantom250YT** [Auxilor/EcoEnchants#177]
**Describe the bug**
Soulbound doesn't seem to be working with netherite tools and bows, it just doesn't allow it to combine in an anvil

**To Reproduce**
1. Get soulbound book
2. Get netherite tool or bow item
3. Place in anvil
4. Doesn't allow you to combine

**Expected behavior**
Allows you to add soulbound to these items

**Server Information (please complete the following information):**
- Version: 1.18.1 PurPur 1560
- Version of plugin: 8.42.0
- Version of eco: 6.25.2

**Comment by WillFP** [comment]
Regenerate your target.yml
