### ISSUE TITLE
Beheading enchant not dropping custom heads

### ISSUE THREAD

**Issue by adognamedspot** [Auxilor/EcoEnchants#180]
When using the Beheading enchant, the only heads that drop are from the Skeleton/Zombie/Creeper mobs. According to the code, the Dragon head should also drop but I have not personally tested that.

By looking at the Beheading.yml config, I would assume that all mobs should be able to drop custom heads (as well as the v8.15.3 changelog)

I have tried this with the default config that uses Endermen, Spider and Cave Spider and could not get those heads to drop either.

[08:07:03 INFO]: This server is running Paper version git-Paper-234 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: c34fb09)
[08:07:37 INFO]: eco version 6.27.2
[08:08:04 INFO]: EcoEnchants version 8.43.6

Attached is the full Beheading.yml
[beheading.yml.txt](https://github.com/Auxilor/EcoEnchants/files/8198973/beheading.yml.txt)

**Comment by WillFP** [comment]
Fixed in next ecoenchants version
