### ISSUE TITLE
Enchant/artifact color code is glitched in the tool tip view.

### ISSUE THREAD

**Issue by TsukiShimoSP** [Auxilor/EcoEnchants#181]
Server info and how the glitch/bug looks like
https://user-images.githubusercontent.com/101145086/157114620-1d1073d5-3024-4b82-ac3a-8a2fc49b7382.png
https://user-images.githubusercontent.com/101145086/157114624-8fee888f-3794-406e-86d6-ce9b979352a8.png

**Comment by WillFP** [comment]
Fixed in latest eco
