### ISSUE TITLE
Bug when trading and enchanting

### ISSUE THREAD

**Issue by WobbyChip** [Auxilor/EcoEnchants#184]
**Describe the bug**
When trading with villagers, trades sometimes doesn't work:
    *Items disappear
    *Getting the wrong item
    *Not getting anything
    *Same happens in survival mode

When enchanting, sometimes some slots are not available
The issue is in the book taken from creative.

**Video**
https://streamable.com/vo2klb

**Server Information (please complete the following information):**

Version: (output of /ver command)
This server is running CraftBukkit version 3452-Spigot-ffceeae-808cb7c (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

Version of plugin and eco (/ver eco, /ver )
[14:46:09 INFO]: eco version 6.27.2
[14:46:11 INFO]: EcoEnchants version 8.44.0

**Comment by Fantom250YT** [comment]
Been having the same issue with purpur.

You just have to make sure you only put 1 book in otherwise it's gets messed up.
