### ISSUE TITLE
Beheading Enchant Custom heads dropped all named "eco's head"

### ISSUE THREAD

**Issue by adognamedspot** [Auxilor/EcoEnchants#185]
Thank you, by the way for fixing the custom head drops as quickly as you did!
Everything seems to work properly, as far as each mob dropping the appropriate head. However, each of the custom heads is named Eco's Head no matter the type.

I would think the heads should be named accordingly (ie: Enderman Head, Wolf Head, etc)

![2022-03-09_00 59 04](https://user-images.githubusercontent.com/36174764/157408903-a5b4bd5d-e458-4a8e-a5cb-2677827a8b1d.png)
![2022-03-09_01 00 25](https://user-images.githubusercontent.com/36174764/157408907-abd3a297-bbe8-482d-bbe3-099f4930e109.png)

[01:01:27 INFO]: This server is running Paper version git-Paper-234 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: c34fb09)
[01:02:05 INFO]: eco version 6.27.3
[01:02:50 INFO]: EcoEnchants version 8.45.0

Again, thank you for an excellent product!

**Comment by WillFP** [comment]
Fixed in latest, add another section to each head that specifies the name:
"enderman::eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTZjMGIzNmQ1M2ZmZjY5YTQ5YzdkNmYzOTMyZjJiMGZlOTQ4ZTAzMjIyNmQ1ZTgwNDVlYzU4NDA4YTM2ZTk1MSJ9fX0=::Enderman's Head"
