### ISSUE TITLE
Could not pass event EntityDeathByEntityEvent to EcoEnchants v8.43.5

### ISSUE THREAD

**Issue by zwrumpy** [Auxilor/EcoEnchants#202]
Versions:
  Paper 1.18.2

Issue:
Could not pass event EntityDeathByEntityEvent to EcoEnchants v8.43.5

Server log:
https://gist.github.com/zwrumpy/dbbf2d440edda64ce9bc12676a2a1fae)

**Comment by WillFP** [comment]
Update to mythicmobs 5.0.0+
