### ISSUE TITLE
Hidden Attributes problem

### ISSUE THREAD

**Issue by MuriloWentz** [Auxilor/EcoEnchants#208]
- Version: ECO = 6.35.2
ECOENCHANTS = 8.60.0

Started happening on the last 2 or 3 updates

It just occurs, after installing the plugin, and it stops after uninstalling them.

![Sem título](https://user-images.githubusercontent.com/50129175/166148772-da9bac53-93db-49a5-a13f-2769500e0006.png)

**Comment by Neeekss** [comment]
Same problem with ecoenchants it show hiden attributes in all guis
![test2](https://user-images.githubusercontent.com/91341783/167292077-ff551fc9-0a04-4b48-b42f-0f509cff80d1.png)

**Comment by WillFP** [comment]
Fixed in latest eco
