### ISSUE TITLE
Does not hide attributes

### ISSUE THREAD

**Issue by MrAnrehah** [Auxilor/EcoEnchants#214]
When creating things using the mythicmobs plugin, when you hide the attributes of things, your plugin shows them, this problem has appeared since version 8.59.3, the plugin also bypasses the restrictions on enchantments

![upload_2022-5-8_14-14-6](https://user-images.githubusercontent.com/32076073/167355002-fb1fc68c-c84d-45cf-ade6-33db0ba26ccd.png).

**Comment by WillFP** [comment]
Fixed in latest eco
