### ISSUE TITLE
hard-cap-clamp doesn't work due to code flaw

### ISSUE THREAD

**Issue by JinOuYongGu** [Auxilor/EcoEnchants#215]
**Describe the bug**
Config hard-cap-clamp option doesn't work
I found it is a code flaw.

how to fix: replace line 465 in file ItemConversions.java
from return; to break;

**To Reproduce**
1. enable the hard-cap-clamp option
2. enchanting an item more than the limit by using /ecoenchant randomenchant
3. drop the item and pick it, the enchants do not clamped
**Expected behavior**
the enchant number should be reduced to limit number

**Screenshots**

**Server Information (please complete the following information):**
- Version: (output of `/ver` command)
- Version of plugin and eco (`/ver eco`, `/ver <plugin>`)

**Additional context**

**Comment by WillFP** [comment]
Thanks!
