### ISSUE TITLE
EcoEnchants taking 75%+ tick

### ISSUE THREAD

**Issue by nf-projects** [Auxilor/EcoEnchants#220]
https://spark.lucko.me/yFQW1Xkn95

- eco 6.35.7
- EcoEnchants 8.67.0
- Eco config https://paste.gg/p/anonymous/fc8ea098b54d48b0acd205ac334b0bfd
- Server is running Pufferfish 1.17.1

**Comment by WillFP** [comment]
I don't understand what's even going on - minecraft is failing to serialize it's own packet? This isn't as much a bug with eco as a bug with ProtocolLib reading the packet; eco just happens to be using that packet.

Maybe try opening a report on ProtocolLib? I really don't know what's happened here
