### ISSUE TITLE
Health being improperly reset on player join

### ISSUE THREAD

**Issue by Opalinium** [Auxilor/EcoEnchants#230]
**Describe the bug**
Due to the fix in [this patch](https://github.com/Auxilor/EcoEnchants/commit/cc00f8b5b95bf9854da86cf4706a914d6e812879) player health is being improperly set to the base vanilla values anytime the player connects to the server
**To Reproduce**
1. Log in to the server

**Expected behavior**
Health should not be reset to base vanilla values every time the player joins, to fix this there should be a minor delay added, or the previously mentioned patch should be redone entirely to prevent this. Effectively players will login to have almost no HP

**Screenshots**

https://user-images.githubusercontent.com/58598304/173155694-5d32d0a4-583e-46b6-b44a-e308fbbae747.mp4

**Server Information (please complete the following information):**
- Version: Purpur-1566 1.18.1
- Version of plugin: 8.80.0
- Version of Eco: 6.36.4

**Additional context**

**Comment by LoJoSho** [comment]
Hmm, unable to replicate on a clean server with Paper-379 1.18.2

https://i.imgur.com/FMmgnjL.gif

Plugins:
Eco 6.36.5
EcoEnchants 8.82.0
EssentialsX 2.19.4
MMOCore 1.9.2
MMOItems 6.7.3
MythicLib 1.3.1
ProtocolLib 4.8.0

Is there any other information that can be given? It might be another plugin that is causing issues with this.

**Comment by Opalinium** [comment]
> Hmm, unable to replicate on a clean server with Paper-379 1.18.2
> 
> https://i.imgur.com/FMmgnjL.gif
> 
> Plugins: Eco 6.36.5 EcoEnchants 8.82.0 EssentialsX 2.19.4 MMOCore 1.9.2 MMOItems 6.7.3 MythicLib 1.3.1 ProtocolLib 4.8.0
> 
> Is there any other information that can be given? It might be another plugin that is causing issues with this.

This issue only started occurring after the prior patch that was mentioned - I'm quite certain its due to how EcoSkills sets the player health attribute.

Relevant Plugins:
Eco 6.37.1
EcoEnchants 8.82.0
EcoArmor 7.76.0
EcoItems 3.71.0
EcoSkills 1.43.0
EssentialsX 2.19.4
ProtocolLib 4.8.0

Regardless of who the player is, their relevant permissions levels or groups, how much health they have, or etc - Every player will login with exactly one heart (And in the context of EcoSkills health scaling, the actual health the player is left with is dependent on what 'one heart' equates to)
