### ISSUE TITLE
Color and text formats of an item name are not kept after combining enchantments

### ISSUE THREAD

**Issue by Complex1t** [Auxilor/EcoEnchants#232]
**Describe the bug**
The color and text formats of an item name are not kept after combining enchantments.

**To Reproduce**
1. Obtain an item named with colors/formats.
2. Combine an enchantment onto the item.
3. Observe that the name colors/formats are reset.

**Expected behavior**
The item name's colors and formats should be kept.

**Video**
[https://i.imgur.com/Uei7lDO.mp4](https://i.imgur.com/Uei7lDO.mp4)

**Server Information (please complete the following information):**
- Version: Paper-379
- Version of plugin: 8.80.1
- Version of eco: 6.36.5

**Additional context**
None

**Comment by WillFP** [comment]
Give the anvil color permission

**Comment by Complex1t** [comment]
The video was tested while opped. Also tested without op with permission `ecoenchants.anvil.color`, still made no difference.
