### ISSUE TITLE
Disable Combining Enchantments

### ISSUE THREAD

**Issue by RJGamers** [Auxilor/EcoEnchants#234]
**Describe the solution you'd like**
Disable players from combining custom enchants (all EcoEnchants) in an anvil but still only allow vanilla enchants to be combined 

**Additional context**
Please could we get a config option to prevent this

**Comment by WillFP** [comment]
Disable anvil in config

**Comment by RJGamers** [comment]
> Disable anvil in config

The 4 options under anvil in the config is already disabled.

**Comment by RJGamers** [comment]
@WillFP

**Comment by RJGamers** [comment]
@WillFP

**Comment by RJGamers** [comment]
> Disable anvil in config

@WillFP please reply.

What you suggested does NOT work.

Thank you
