### ISSUE TITLE
LandsDiscordBot plugin Support

### ISSUE THREAD

**Issue by Jwaffles04** [Auxilor/EcoEnchants#236]
Eco plugins are incompatible with LandsDiscordBot. 
Although it is compatible with Lands by itself.

![Screenshot 2022-06-14 184402](https://user-images.githubusercontent.com/18368751/174222616-a0c57852-1255-4897-bed5-9222c80a5e21.png)

**Comment by LuluxClient** [comment]
This isn't eco's fault I think, dm the dev of Lands to fix it.
