### ISSUE TITLE
The new minecraft enchant, Swift Sneak, does not work properly EcoEnchants

### ISSUE THREAD

**Issue by baailey** [Auxilor/EcoEnchants#237]
**Describe the bug**
The Swift Sneak enchant will show as a [blank book](https://i.imgur.com/APIWv0S.png) when found through natural generation (ancient city, spawner chest etc.). When adding the book to my [lang.yml](https://i.imgur.com/hbunkv3.png) it displayed the name and description properly, auto-fixing itself upon double-clicking, however the enchant does not apply to an item through an anvil.

**To Reproduce**
1. Generate a fresh EcoEnchants folder
2. Find a naturally generated chest
3. Try put the enchant in an anvil with an item

**Expected behavior**
The Enchant name and description should display upon first discovery, and should apply to an item through an anvil.

**Screenshots**

**Server Information (please complete the following information):**
- Version: git-Paper-23 (MC: 1.19)
- Version of plugin and eco: eco version 6.37.1,  EcoEnchants version 8.82.0

**Additional context**

**Comment by WillFP** [comment]
Fixed!
