### ISSUE TITLE
Errors at compiling the EcoEnchant

### ISSUE THREAD

**Issue by iDanEzz** [Auxilor/EcoEnchants#243]
Execution failed for task ':eco-core:core-plugin:compileJava'.
> Could not resolve all files for configuration ':eco-core:core-plugin:compileClasspath'.
   > Could not resolve io.lumine:Mythic:5.0.1.
     Required by:
         project :eco-core:core-plugin
      > Could not resolve io.lumine:Mythic:5.0.1.
         > Could not get resource 'https://org.kitteh.pastegg/io/lumine/Mythic/5.0.1/Mythic-5.0.1.pom'.
            > Could not GET 'https://org.kitteh.pastegg/io/lumine/Mythic/5.0.1/Mythic-5.0.1.pom'.
               > No such host is known (org.kitteh.pastegg)
      > Could not resolve io.lumine:Mythic:5.0.1.
         > Could not get resource 'https://maven.sk89q.com/repo/io/lumine/Mythic/5.0.1/Mythic-5.0.1.pom'.
            > Could not GET 'https://maven.sk89q.com/repo/io/lumine/Mythic/5.0.1/Mythic-5.0.1.pom'. Received status code 503 from server: Service Unavailable
   > Could not resolve io.lumine:LumineUtils:1.16.1-SNAPSHOT.
     Required by:
         project :eco-core:core-plugin
      > Could not resolve io.lumine:LumineUtils:1.16.1-SNAPSHOT.
         > Could not get resource 'https://repo.dustplanet.de/artifactory/ext-release-local/io/lumine/LumineUtils/1.16.1-SNAPSHOT/LumineUtils-1.16.1-SNAPSHOT.pom'.
            > Could not HEAD 'https://repo.dustplanet.de/artifactory/ext-release-local/io/lumine/LumineUtils/1.16.1-SNAPSHOT/LumineUtils-1.16.1-SNAPSHOT.pom'. Received status code 409 from server: Conflict
      > Could not resolve io.lumine:LumineUtils:1.16.1-SNAPSHOT.
         > Unable to load Maven meta-data from https://org.kitteh.pastegg/io/lumine/LumineUtils/1.16.1-SNAPSHOT/maven-metadata.xml.
            > Could not GET 'https://org.kitteh.pastegg/io/lumine/LumineUtils/1.16.1-SNAPSHOT/maven-metadata.xml'.
               > org.kitteh.pastegg
      > Could not resolve io.lumine:LumineUtils:1.16.1-SNAPSHOT.
         > Unable to load Maven meta-data from https://maven.sk89q.com/repo/io/lumine/LumineUtils/1.16.1-SNAPSHOT/maven-metadata.xml.
            > Could not GET 'https://maven.sk89q.com/repo/io/lumine/LumineUtils/1.16.1-SNAPSHOT/maven-metadata.xml'. Received status code 503 from server: Service Unavailable

**Comment by LoJoSho** [comment]
You are compiling an outdated version of EcoEnchants, redownload with #235 and see if that resolves the problem.
