### ISSUE TITLE
Swift sneak enchantment lore glitches out

### ISSUE THREAD

**Issue by cloakfox** [Auxilor/EcoEnchants#245]
As title says, currently when you grab a swift sneak enchanted book out of the vanilla creative menu and put it in your hotbar, the ecoenchants lore is not displayed

I am currently using the 1.19 supported version of Ecoenchants

v 8.86.
![2022-06-19_22 35 54](https://user-images.githubusercontent.com/3696645/174499538-1ffbf2ca-a805-4f17-89ba-ac1c6c1f4a2b.png)
0

**Comment by WillFP** [comment]
Fixed!
