### ISSUE TITLE
grindstoneable option in customenchants.yml does not work

### ISSUE THREAD

**Issue by KermX** [Auxilor/EcoEnchants#246]
**Describe the bug**
Despite the grindstoneable option being set to false for an enchant in customenchants.yml you can still use a grindstone to remove the enchantment

**To Reproduce**
1. Create an enchant in customenchants.yml
2.  Set grindstoneable to false
3. Observe that you can still remove the enchantment with a grindstone

**Expected behavior**
Option should make the enchant un-grindstoneable

**Server Information (please complete the following information):**
- Version: git-PufferfishPlus-18
- Version Eco: eco version 6.37.1
- Version EcoEnchants: EcoEnchants version 8.86.0

**Comment by WillFP** [comment]
Fixed!
