### ISSUE TITLE
Sneak Swift Enchantment Bug

### ISSUE THREAD

**Issue by AccioAce** [Auxilor/EcoEnchants#254]
**Describe the bug**
the swift sneak enchantment books are a glitch. When players loot them from the ancient city or taken out from creative mode the enchantment book name disappears -> https://gyazo.com/f1d42c2b967dbd73be3ba25cb8437959 

**To Reproduce**
Steps to reproduce the behavior: Explained above ^ and provided a short gif video as well.

**Expected behavior**

**Screenshots**
Same screenshot from above -> https://gyazo.com/f1d42c2b967dbd73be3ba25cb8437959 

**Server Information (please complete the following information):**
- Version: Paper 1.19
- Version of plugin: 8.93.0
- Eco Version: 6.37.1

**Additional context**
Not that I know of, but it does need fixing asap.

**Comment by WillFP** [comment]
Fixed!
