### ISSUE TITLE
Performance issue with calling search functions upon chunk loading

### ISSUE THREAD

**Issue by Akiranya** [Auxilor/EcoEnchants#255]
**Describe the bug**
This performance issue was mentioned in the comment section of spigot page. The original comment was already clear so I will just copy the issue desciption over here:

```
The biggest turn away issue that got my attention, was how EcoEnchants modified the core gameplay of calling the search feature function on maps in chests on chunk load rather than on chest opening.

Now, why is this such a big deal? The biggest reason, is this can cause treasure maps to completely freeze your server when a single player walks near one of them in a chunk, and possibly several of them which can crash the server on chunk generation or chunk load.
```

Here is the screenshot of the full comment:
![image](https://user-images.githubusercontent.com/14846342/176103473-26380b02-39bc-4abe-a1aa-a18e2b38ce39.png)

Here the is stacktrace when server is stuck by eco calling loot functions upon chunk generation: https://pastebin.com/dPPYjwL6. Without EcoEnchants, the chunk generation is just super fast without any lag.

**To Reproduce**

Method 1 (harder):
1. Make enough amount of enchantbooks that will spawn in lootchest
2. For test purpose, making all enchantbooks spawn in lootchest can detect the issue quickly
3. Locating lootchest by using `/locate structure` ([usage](https://minecraft.fandom.com/wiki/Commands/locate)) command
4. TP to those lootchest and watch TPS / MSPT to observe the performance issue

Method 2 (eaiser):
1. Make enough amount of enchantbooks that will spawn in lootchest
2. Use some chunk pre-generation plugin like Chunky to genenerate the world chunks
3. See console for the `server not responding` warnings

**Expected behavior**
As stated in the comment, the enchantbooks should be put in the lootchest upon open rather than chunk generation.

**Screenshots**

**Server Information (please complete the following information):**
- Version: Current: git-Purpur-1684 (MC: 1.19)*
- Version of plugin and eco: 8.93.0

**Additional context**
I am not the author of the comment in the screenshot but the comment really draws my attention too. I hope Auxilor can take this issue into consideration. I understand that EcoEnchants has already been improved a lot regarding to performance but I really hope it can run faster.

**Comment by WillFP** [comment]
Can you move this to a feature request for having loot generation be done on container open?

**Comment by Akiranya** [comment]
> having loot generation be done on container open

Sure! here is the [feature request](https://github.com/Auxilor/EcoEnchants/issues/255).

**Comment by Geoxor** [comment]
Yeah this would be a nice fix since it really hogs the tps down
![image](https://user-images.githubusercontent.com/34042825/177328173-e10f1387-5b0b-4b64-9a53-b1fa98dc5664.png)
