### ISSUE TITLE
Swift Sneak cannot be applied to items

### ISSUE THREAD

**Issue by baailey** [Auxilor/EcoEnchants#257]
**Describe the bug**
Swift Sneak cannot be applied to an item through an anvil

**To Reproduce**
1. Give yourself the Swift Sneak enchantment book
2. Try apply it to an item through an anvil

**Expected behavior**
It should apply

**Screenshots**

**Server Information (please complete the following information):**
- Version: git-Paper-27 (MC: 1.19) 
- Version of plugin and eco: eco 6.37.1, EcoEnchants 8.93.2

**Additional context**

**Comment by WillFP** [comment]
Swift sneak is for leggings not boots - I can confirm it works correctly
