### ISSUE TITLE
Enchantment slots

### ISSUE THREAD

**Issue by PixelSpell** [Auxilor/EcoEnchants#284]
Hi, I was thinking enchantment slots could be a great addition for the plugin. You'd need a special item to place it on the item to add an enchantment slot. When a slot is created a player could place only 1 enchantment on the item. When they create more slots, they'll be able to place enchantments on the item eg.: 5 slots equals 5 enchantments. etc...

My other idea is to separate the artifact enchantments from the normal ones. Artifacts take 1 enchantment slot. When you set up a max number of enchantments let's say 10. It can be frustrating when  an artifact is one of them.

**Comment by WillFP** [comment]
This has been suggested in the past, but I don't plan on doing this, it doesn't really fit the style of the plugin for me. I do plan on having the enchantment limits be customizable per-type, however.
