### ISSUE TITLE
Items losing enchant visibility

### ISSUE THREAD

**Issue by MillionthOdin16** [Auxilor/EcoEnchants#303]
I think there's an issue with unintended hiding of enchants in this section of code (66d06d7a4a36109b6de232f55709ef5f35f72ecc). I've had a number of players lose the enchantments on their items, which we later realized was just hiding of the enchantments. Both the hide enchants and ecoenchant-lore options become set, and enchants stay hidden even when the hide enchants flag is unset manually (I think it stays hidden because I cannot unset ecoenchant-lore).

We noticed the issue after messing around with a drugs plugin that gives items that have hidden enchant/potion effects. We use the items and then the potion effect becomes active, and the item is consumed. I assume this is somehow causing eco to apply the hide flag to unrelated items.

**Server Information (please complete the following information):**
- Version: git-Purpur-1788 (MC: 1.19.2)*
 eco version 6.41.1
 EcoEnchants version 9.0.0-b30

**Additional context**
This might be related to #299

![image](https://user-images.githubusercontent.com/102247808/192083740-5c07eb7f-035a-4ed6-a014-3a1f0a7c611c.png)

**Comment by 0ft3n** [comment]
> I think there's an issue with unintended hiding of enchants in this section of code ([66d06d7](https://github.com/Auxilor/EcoEnchants/commit/66d06d7a4a36109b6de232f55709ef5f35f72ecc)). I've had a number of players lose the enchantments on their items, which we later realized was just hiding of the enchantments. Both the hide enchants and ecoenchant-lore options become set, and enchants stay hidden even when the hide enchants flag is unset manually (I think it stays hidden because I cannot unset ecoenchant-lore).
> 
> We noticed the issue after messing around with a drugs plugin that gives items that have hidden enchant/potion effects. We use the items and then the potion effect becomes active, and the item is consumed. I assume this is somehow causing eco to apply the hide flag to unrelated items.
> 
> **Server Information (please complete the following information):**
> 
> * Version: git-Purpur-1788 (MC: 1.19.2)*
>   eco version 6.41.1
>   EcoEnchants version 9.0.0-b30
> 
> **Additional context** This might be related to #299
> 
> ![image](https://user-images.githubusercontent.com/102247808/192083740-5c07eb7f-035a-4ed6-a014-3a1f0a7c611c.png)

The code you are reffering to is checking if item had hide enchants flag before the display so it's not an issue, it's how it works

**Comment by MillionthOdin16** [comment]
But this is the only code that deals with `ecoenchatlore-hide`. And that is what is being applied to the item incorrectly.

**Comment by MillionthOdin16** [comment]
This commit in eco should have resolved this issue https://github.com/Auxilor/eco/commit/82d269daf11876dd6722e130562fb6196210b53a

**Comment by MillionthOdin16** [comment]
Close resolved
