### ISSUE TITLE
bug when starting server

### ISSUE THREAD

**Issue by LautaKooh** [Auxilor/EcoEnchants#304]
**Describe the bug**
This error appears when starting the server, https://pastebin.com/J9hLcEDw

**To Reproduce**
Start server

**Server Information (please complete the following information):**
- Version: get-petal-"cc713" (MC 1.19.2)
- Version of plugin and eco: eco version 6.41.1 EcoEnchants version 9.0.0-b30

**Comment by WillFP** [comment]
Fixed
