### ISSUE TITLE
Failed to start thread - pthread_create failed

### ISSUE THREAD

**Issue by hwalker928** [Auxilor/EcoEnchants#335]
**Describe the bug**
Using EcoEnchants causes the following error `[44.062s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.` for too many threads being created. 

After looking through the Discord support channels, it seems a couple of other people have also had this issue, with the only recommendation being to either switch hosts, or contact Pterodactyl support. However, it seems to be an issue with the plugin itself.

**To Reproduce**
Steps to reproduce the behaviour: 
1. Install EcoEnchants@9.12.1 and eco@6.47.0
2. See thread-related error messages in the console

**Expected behaviour**
The plugin does not create an excessive amount of threads.

**Server Information (please complete the following information):**
- Version: git-Purpur-1857 (MC: 1.19.2)*
- EcoEnchants@9.12.1 and eco@6.47.0

**Additional context**
Using Pterodactyl with default PID settings.
Also, I have never experienced this error before, so it may be caused by a recent EcoEnchants update.

**Comment by D3dWiz** [comment]
I have the same issue, also using pterodactyl server.
