### ISSUE TITLE
Ecoenchants Nan health problem

### ISSUE THREAD

**Issue by stevesensei** [Auxilor/EcoEnchants#346]
**Describe the bug**

I'm using a sword to hit a player,But when I hit,his health became Nan and he can't be damaged anymore until he rejoin the server
The sword and Nan health player

**To Reproduce**
1. Enchant a weapon that with HUGE damage(may over 20?I'm not so sure)
2. Hit a player
3. player health became Nan
4. Until he rejoin,he can't be damaged anymore

**Expected behavior**
On the side of the player that be hitted,his health doesn't change

**Screenshots**

![Enchantments](https://user-images.githubusercontent.com/32810212/213951168-01f5775c-f2fe-4f3c-9713-66f31acf91d5.png)

![2023-01-23_08 35 23](https://user-images.githubusercontent.com/32810212/213951217-fc67a6e4-3986-403e-815f-3d1ae870f27f.png)

**Server Information (please complete the following information):**
Server version: purpur(paper) 1.19.3
Plugin version: 9.15.7
eco Version: 6.48.2

**Comment by stevesensei** [comment]
When I hit mobs,it has no problem

**Comment by WillFP** [comment]
Please report bugs on the discord! This is actively being worked on, and I'm asking for testers currently
