### ISSUE TITLE
[Lag Spikes] Swords with long lore cause huge amounts of lag spikes when hitting multiple enemies

### ISSUE THREAD

**Issue by Rixic** [Auxilor/EcoEnchants#43]
having a custom sword with even 10 lines of lore causes a noticable lag spike when hitting a full swing (and hitting multiple enemies) at once, im assuming it's because it's reading the lore for each damage instance and since there's let's say 20 hit mobs in a grinder at the low end, it's reading those 10 lines 20 times all at one instant and comparing it to the enchants list.

I've tested on a clean server install with ecoenchants and protocollib latest etc etc and have video of it in action.
Where I test a sword with no lore, and a sword with 10 lines of junk lore and there's a huge spike with the sword with lore.

I'm not sure what you would do to fix this but this currently makes the plugin unusable for me as im using custom items with decents amount of lore and this just causes the server to stutter everytime a player hits more than a couple of mobs.

**Comment by Auxilor** [comment]
Yeah - no.
EcoEnchants doesn't use lore-based enchants
They're registered with spigot and function identically to vanilla enchantments: they work with the api.
Join my discord (linked on readme iirc) and send me a spark profile.
