### ISSUE TITLE
Could not resolve host

### ISSUE THREAD

**Issue by Temporaly001** [Auxilor/EcoEnchants#49]
Cannot download eco-5.5.1.pom because website org.kitteh.pastegg is down.

Execution failed for task ':eco-core:core-proxy:compileJava'.
> Could not resolve all files for configuration ':eco-core:core-proxy:compileClasspath'.
   > Could not resolve com.willfp:eco:5.5.1.
     Required by:
         project :eco-core:core-proxy
      > Could not resolve com.willfp:eco:5.5.1.
         > Could not get resource 'https://org.kitteh.pastegg/com/willfp/eco/5.5.1/eco-5.5.1.pom'.
            > Could not GET 'https://org.kitteh.pastegg/com/willfp/eco/5.5.1/eco-5.5.1.pom'.
               > No such host is known (org.kitteh.pastegg)

**Comment by SprigWave** [comment]
i may be wrong but i think its looking for a pom file from a bunch of different hosts and they're all up but this one is down and it screws up the compilation

**Comment by Guest0070** [comment]
Any solution for it yet?

**Comment by SprigWave** [comment]
> Any solution for it yet?

(If anything in this text is inside of double quotes that means that they are not to be actually pasted as a command or as a string to erase in a txt file.)

Ok I have a solution.
Download the EcoEnchants source code and the eco source code from here https://github.com/Auxilor/EcoEnchants/archive/refs/tags/7.8.11.zip
and here
https://github.com/Auxilor/eco/archive/refs/tags/5.5.1.zip

Extract the eco zip file and then open a command prompt and then CD into the folder where the eco main project directory is. So lets say eco is in my downloads I would run the command "cd C:\Users\USERNAME\Downloads\eco-5.5.1\eco-5.5.1"

Then once nested in the directory type "gradlew build"
Once it's done (i don't know of any reasons why it would error) exit the directory and then extract the EcoEnchants zip file.

Once in here before attempting to build it go into the main project folder and open build.gradle as a text file.
Then remove the line that reads 
"        maven { url 'https://org.kitteh.pastegg' }"
then save the file. Go back to or open a new command prompt and then CD into the folder where the EcoEnchants main project directory is. Lets say mine is in my downloads, I would run 
"cd C:\Users\USERNAME\Downloads\EcoEnchants-7.8.11\EcoEnchants-7.8.11"
Once in this directory run "gradlew build"
If the build succeeds ( I don't know why it wouldn't) navigate to EcoEnchants-7.8.11\bin and in there you should find the EcoEnchants jar file.

I'm sorry if this guide is hard to understand as I am terrible at giving instructions. If you need further help send me a friend request on discord at SprigWave#4219

**Comment by Temporaly001** [comment]
> > Any solution for it yet?
> 
> (If anything in this text is inside of double quotes that means that they are not to be actually pasted as a command or as a string to erase in a txt file.)
> 
> Ok I have a solution.
> Download the EcoEnchants source code and the eco source code from here https://github.com/Auxilor/EcoEnchants/archive/refs/tags/7.8.11.zip
> and here
> https://github.com/Auxilor/eco/archive/refs/tags/5.5.1.zip
> 
> Extract the eco zip file and then open a command prompt and then CD into the folder where the eco main project directory is. So lets say eco is in my downloads I would run the command "cd C:\Users\USERNAME\Downloads\eco-5.5.1\eco-5.5.1"
> 
> Then once nested in the directory type "gradlew build"
> Once it's done (i don't know of any reasons why it would error) exit the directory and then extract the EcoEnchants zip file.
> 
> Once in here before attempting to build it go into the main project folder and open build.gradle as a text file.
> Then remove the line that reads
> " maven { url 'https://org.kitteh.pastegg' }"
> then save the file. Go back to or open a new command prompt and then CD into the folder where the EcoEnchants main project directory is. Lets say mine is in my downloads, I would run
> "cd C:\Users\USERNAME\Downloads\EcoEnchants-7.8.11\EcoEnchants-7.8.11"
> Once in this directory run "gradlew build"
> If the build succeeds ( I don't know why it wouldn't) navigate to EcoEnchants-7.8.11\bin and in there you should find the EcoEnchants jar file.
> 
> I'm sorry if this guide is hard to understand as I am terrible at giving instructions. If you need further help send me a friend request on discord at SprigWave#4219

Thanks, this actually worked!

**Comment by Super-10** [comment]
The latest version link:https://jitpack.io/com/github/Auxilor/EcoEnchants/master-3dda4db98f-1/EcoEnchants-master-3dda4db98f-1.jar
