### ISSUE TITLE
Enchanted book in villager trade displayed incorrectly

### ISSUE THREAD

**Issue by iZeroneX** [Auxilor/EcoEnchants#64]
![photo](https://user-images.githubusercontent.com/13903138/133884328-4414c52c-effb-4f49-9152-248da3947b61.png)

The result was not displayed. However, it can be traded successfully by clicking this 'air' item.

Protocollib/eco/Ecoenchant are all in the latest versions.

**Comment by EvergreenOne** [comment]
Supplement
![pw1](https://user-images.githubusercontent.com/13903138/133892191-caf2960f-1a4b-498c-b958-6cb1e2db96af.png)

**Comment by JMCY26** [comment]
I can confirm we're having this issue also, disabling the eco plugins has restored correct GUI for trades.

**Comment by kelegele** [comment]
@WillFP @JMCY26  This bug happened again
EcoEnchants  10.20.1
Minecraft 1.20.1
paper-1.20.1-43
