### ISSUE TITLE
Griefdefender Issue - Could not pass event [AllEvents]

### ISSUE THREAD

**Issue by Parthurax** [Auxilor/EcoEnchants#82]
MC: 1.17.1 PurPur
Ecos: Updated yesterday all Eco resources so i believe the newest ones.

Hi i got this error message:
https://paste.gg/p/anonymous/1c302ac50caf44bcaae7f496e998d7ee

This is spamming my console non stop ofc.
My console is not use able atm.. So its very important to me to get this fixed.

**Comment by Uharn** [comment]
+1 here i have the same issue
